---
- name: Patch
  hosts: nxos_vteps
  gather_facts: no
  vars:
    my_patch: nxos_patch.rpm
    my_ver: 7.0(3)I7(5)

  tasks:
    - name: Get the NX-OS version
      nxos_facts:
        gather_subset: "!interfaces"

    - debug:
        var: ansible_net_version

    - name: Apply OSPF patch
      debug:
        msg: "Applying the patch"
      changed_when: True
      when: ansible_net_version == "{{ my_ver }}"
      notify:
        - Get OSPF neighbors
        - Display OSPF neighbors

  handlers:
    - name: Get OSPF neighbors
      nxos_command:
        commands: ["show ip ospf neighbors"]
      register: ospf_neighbors

    - name: Display OSPF neighbors
      debug:
        var: ospf_neighbors
