---
- name: Destroy L2VNI
  hosts: nxos_vteps_nxapi

  tasks:
    - name: Remove L2VNI from Overlay
      nxos_vxlan_vtep_vni:
        interface: nve1
        vni: 20200
        # FIXME
        provider: "{{ nxapi_provider }}"
