---
- name: Destroy L2VNI
  hosts: nxos_vteps_nxapi
  gather_facts: no

  tasks:
    - name: Remove L2VNI from Overlay
      nxos_vxlan_vtep_vni:
        interface: nve1
        vni: FIXME_L2VNI
        FIXME_parameter: FIXME_value
        provider: "{{ nxapi_provider }}"
