---
- name: Patch
  hosts: nxos_vteps
  gather_facts: no
  vars:
    my_patch: nxos_patch.rpm
    my_ver: 7.0(3)I7(5)

  tasks:
    - name: Get the NX-OS version
      nxos_facts:
        gather_subset: "!interfaces"

    - debug:
        var: FIXME

    - name: Apply OSPF patch
      debug:
        msg: "Applying the patch"
      when: FIXME == "{{ my_ver }}"
