---
- name: Ping all underlay switches
  hosts: nxos_vteps
  gather_facts: no

  tasks:
    - name: Ping all underlay switches
      nxos_ping:
        dest: "{{ item }}"
        vrf: management
      loop:
        - FIXME
        - FIXME
        - FIXME
