---
- name: Ping
  hosts: workshop_admin
  gather_facts: no

  tasks:
    - name: Get the NX-OS version
      nxos_facts:
        gather_subset: "!interfaces"

    - debug:
        var: ansible_net_version

    - name: Ping
      nxos_ping:
        dest: 171.70.168.183
        vrf: management

    - name: Get users
      nxos_command:
        commands:
          - command: "show user-account | i user: | sort"
            output: text
      register: users

    # - debug: var=users.stdout

    - name: Check student users
      assert:
        that: users.stdout[0] is search('student10\nuser:student11\nuser:student12\nuser:student13\nuser:student14\nuser:student15\nuser:student16\nuser:student17\nuser:student18\nuser:student19\nuser:student20\nuser:student21\nuser:student22\nuser:student23\nuser:student24\nuser:student25\nuser:student26\nuser:student27\nuser:student28\nuser:student29\nuser:student30\nuser:student31\nuser:student32\nuser:student33\nuser:student34\nuser:student35\nuser:student36\nuser:student37\nuser:student38\nuser:student39\nuser:student40\nuser:student41\nuser:student42\nuser:student43\nuser:student44\nuser:student45\nuser:student46\nuser:student47\nuser:student48\nuser:student49\nuser:student50\nuser:student51\nuser:student52\nuser:student53\nuser:student54\nuser:student55\nuser:student56\nuser:student57\nuser:student58\nuser:student59\nuser:student60\nuser:student61\nuser:student62\nuser:student63\nuser:student64\nuser:student65\nuser:student66\nuser:student67\nuser:student68\nuser:student69\nuser:student70\nuser:student71\nuser:student72\nuser:student73\nuser:student74\nuser:student75\nuser:student76\nuser:student77\nuser:student78\nuser:student79\nuser:student80\nuser:student81\nuser:student82\nuser:student83\nuser:student84\nuser:student85\nuser:student86\nuser:student87\nuser:student88\nuser:student89\nuser:student90')
