---
- name: Compare config
  hosts: nxos_vteps
  gather_facts: no

  tasks:
    - name: Compare config
      nxos_config:
        diff_against: intended
        intended_config: "{{ lookup('file', 'master_clean.cfg') }}"
        diff_ignore_lines:
          - 'username*'
          - 'snmp-server*'
          - 'hostname*'
          - 'vdc*'
          - 'vrf context management*'
          - 'interface mgmt0*'

