---
- name: Configure vPC
  hosts: vpc
  gather_facts: no

  tasks:
    - name: Enable features
      nxos_feature:
        feature: "{{ item }}"
      loop:
        - lacp
        - vpc

    - name: Add vPC domain and peer-keepalive
      nxos_vpc:
        domain: "{{ vpc_domain }}"
        peer_gw: yes
        pkl_src: "{{ pkl_src }}"
        pkl_dest: "{{ pkl_dest }}"

    - name: Add peer-link port-channel
      nxos_interface:
        name: "port-channel{{ peer_link_po }}"
        mode: layer2

    - name: Configure peer-link PO as trunk
      nxos_l2_interface:
        name: "port-channel{{ peer_link_po }}"
        mode: trunk

    - name: Configure peer-link PO as vPC peer-link
      nxos_vpc_interface:
        portchannel: "{{ peer_link_po }}"
        peer_link: true

    - name: Configure and unshut peer-link interfaces
      nxos_interface:
        aggregate: "{{ peer_link_interfaces }}"
        mode: layer2
        admin_state: up

    - name: Configure peer-link interfaces as trunk
      nxos_l2_interface:
        aggregate: "{{ peer_link_interfaces }}"
        mode: trunk

    - name: Add peer-link interfaces as member of the peer-link PO
      nxos_linkagg:
        group: "{{ peer_link_po }}"
        mode: active
        members: "{{ peer_link_members }}"
