---
- name: Get L2VNI {{ item.id }}
  nxos_command:
    commands: show nve vni {{ item.id }}
  register: output

- name: check
  block:
    - assert:
        that:
          - output.stdout[0] != ""
        fail_msg: "L2VNI {{ item.id }} missing"
  rescue:
    - nxos_command:
        commands: show run int nve1
      register: sh_run
    - debug: var=sh_run.stdout_lines

