---
- hosts: nxos_vteps
  gather_facts: no
  connection: network_cli

  tasks:
    - name:  Merge device configuration with provided configuration.
      nxos_vlans:
        config:
          - { vlan_id: 11, name: production-vlan11}
          - { vlan_id: 12, name: production-vlan12}
          - { vlan_id: 500, name: test-vlan500}
        state: merged
