---
- name: Delete L2VNI
  hosts: 93180-1 93180-2
  connection: local
  gather_facts: no

  vars_files:
    - external_vars.yml

  tasks:
    - name: Reset access port VLAN
      nxos_switchport:
        interface: "{{ interface }}"
        mode: access
        access_vlan: 1
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: "{{ transport }}"

    - name: Remove L2VNI from EVPN
      nxos_evpn_vni:
        vni: "{{ vni }}"
        state: absent
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: "{{ transport }}"

    - name: Remove L2VNI from Overlay
      nxos_vxlan_vtep_vni:
        interface: nve1
        vni: "{{ vni }}"
        state: absent
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: "{{ transport }}"

    - name: Remove VLAN
      nxos_vlan:
        vlan_id: "{{ vlan }}"
        mapped_vni: "{{ vni }}"
        state: absent
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: "{{ transport }}"

