---
- name: Patch
  hosts: nxos_vteps_nxapi
  vars:
    my_patch: nxos.CSCve91311-n9k_ALL-1.0.0-7.0.3.I6.1.lib32_n9000.rpm
    my_ver: 7.0(3)I6(1)

  tasks:
    - name: Get the NX-OS version
      nxos_facts:
        gather_subset: "!interfaces"
        provider: "{{ nxapi_provider }}"

    - debug:
        var: ansible_net_version

    - name: Apply OSPF patch
      nxos_smu:
        pkg: "{{ my_patch }}"
        provider: "{{ nxapi_provider }}"
      when: ansible_net_version == "{{ my_ver }}"
      notify:
        - Get OSPF neighbors
        - Display OSPF neighbors

  handlers:
    - name: Get OSPF neighbors
      nxos_command:
        commands: ["show ip ospf neighbors"]
        provider: "{{ nxapi_provider }}"
      register: ospf_neighbors

    - name: Display OSPF neighbors
      debug:
        var: ospf_neighbors
