---
topology:
  # -------
  interfaces:
    sp1: [loopback1, Ethernet1/1, Ethernet1/2, Ethernet1/3, Ethernet1/4]
    sp2: [loopback1, Ethernet1/1, Ethernet1/2, Ethernet1/3, Ethernet1/4]
    lf1: [loopback0, loopback1, Ethernet1/1, Ethernet1/2]
    lf2: [loopback0, loopback1, Ethernet1/1, Ethernet1/2]
    lf3: [loopback0, loopback1, Ethernet1/1, Ethernet1/2]
    lf4: [loopback0, loopback1, Ethernet1/1, Ethernet1/2]
  ethernet:
    sp1: [Ethernet1/1, Ethernet1/2, Ethernet1/3, Ethernet1/4]
    sp2: [Ethernet1/1, Ethernet1/2, Ethernet1/3, Ethernet1/4]
    lf1: [Ethernet1/1, Ethernet1/2]
    lf2: [Ethernet1/1, Ethernet1/2]
    lf3: [Ethernet1/1, Ethernet1/2]
    lf4: [Ethernet1/1, Ethernet1/2]

  loopbacks_base:
    sp1:
      - { name: loopback1,   description: UNDERLAY_BGP_EVPN }
    sp2:
      - { name: loopback1,   description: UNDERLAY_BGP_EVPN }
    lf1:
      - { name: loopback0,   description: UNDERLAY_VXLAN_VTEP }
      - { name: loopback1,   description: UNDERLAY_BGP_EVPN }
    lf2:
      - { name: loopback0,   description: UNDERLAY_VXLAN_VTEP }
      - { name: loopback1,   description: UNDERLAY_BGP_EVPN }
    lf3:
      - { name: loopback0,   description: UNDERLAY_VXLAN_VTEP }
      - { name: loopback1,   description: UNDERLAY_BGP_EVPN }
    lf4:
      - { name: loopback0,   description: UNDERLAY_VXLAN_VTEP }
      - { name: loopback1,   description: UNDERLAY_BGP_EVPN }

  ethernet_base:
    sp1:
      - { name: Ethernet1/1, description: UNDERLAY, enabled: True, mode: 'layer3' }
      - { name: Ethernet1/2, description: UNDERLAY, enabled: True, mode: 'layer3' }
      - { name: Ethernet1/3, description: UNDERLAY, enabled: True, mode: 'layer3' }
      - { name: Ethernet1/4, description: UNDERLAY, enabled: True, mode: 'layer3' }
    sp2:
      - { name: Ethernet1/1, description: UNDERLAY, enabled: True, mode: 'layer3' }
      - { name: Ethernet1/2, description: UNDERLAY, enabled: True, mode: 'layer3' }
      - { name: Ethernet1/3, description: UNDERLAY, enabled: True, mode: 'layer3' }
      - { name: Ethernet1/4, description: UNDERLAY, enabled: True, mode: 'layer3' }
    lf1:
      - { name: Ethernet1/1, description: UNDERLAY, enabled: True, mode: 'layer3' }
      - { name: Ethernet1/2, description: UNDERLAY, enabled: True, mode: 'layer3' }
    lf2:
      - { name: Ethernet1/1, description: UNDERLAY, enabled: True, mode: 'layer3' }
      - { name: Ethernet1/2, description: UNDERLAY, enabled: True, mode: 'layer3' }
    lf3:
      - { name: Ethernet1/1, description: UNDERLAY, enabled: True, mode: 'layer3' }
      - { name: Ethernet1/2, description: UNDERLAY, enabled: True, mode: 'layer3' }
    lf4:
      - { name: Ethernet1/1, description: UNDERLAY, enabled: True, mode: 'layer3' }
      - { name: Ethernet1/2, description: UNDERLAY, enabled: True, mode: 'layer3' }

  loopbacks_l3:
    sp1:
      - { name: loopback1,   ipv4: [address: 10.10.10.101/32] }
    sp2:
      - { name: loopback1,   ipv4: [address: 10.10.10.102/32] }
    lf1:
      - { name: loopback0,   ipv4: [address: 10.200.200.1/32] }
      - { name: loopback1,   ipv4: [address: 10.10.10.1/32] }
    lf2:
      - { name: loopback0,   ipv4: [address: 10.200.200.2/32] }
      - { name: loopback1,   ipv4: [address: 10.10.10.2/32] }
    lf3:
      - { name: loopback0,   ipv4: [address: 10.200.200.3/32] }
      - { name: loopback1,   ipv4: [address: 10.10.10.3/32] }
    lf4:
      - { name: loopback0,   ipv4: [address: 10.200.200.4/32] }
      - { name: loopback1,   ipv4: [address: 10.10.10.4/32] }


  ospf:
    sp1:
      router_id: 10.10.10.101
    sp2:
      router_id: 10.10.10.102
    lf1:
      router_id: 10.10.10.1
    lf2:
      router_id: 10.10.10.2
    lf3:
      router_id: 10.10.10.3
    lf4:
      router_id: 10.10.10.4

  hosts_base:
    ha: { name: Ethernet1/1, ip: 192.168.0.10/24, gw: 192.168.0.1 }
    hb: { name: Ethernet1/1, ip: 192.168.0.10/24, gw: 192.168.0.1 }
    hc: { name: Ethernet1/1, ip: 192.168.0.20/24, gw: 192.168.0.1 }
    hd: { name: Ethernet1/1, ip: 192.168.10.20/24, gw: 192.168.10.1 }

  ip_verify_list:
    - 10.10.10.1
    - 10.10.10.2
    - 10.10.10.3
    - 10.10.10.4
    - 10.10.10.101
    - 10.10.10.102
    - 10.200.200.1
    - 10.200.200.2
    - 10.200.200.3
    - 10.200.200.4

  bgp:
    leaf_neighbors:
      - 10.10.10.101
      - 10.10.10.102
    spine_neighbors:
      - 10.10.10.1
      - 10.10.10.2
      - 10.10.10.3
      - 10.10.10.4
